# Generated by Django 3.1.5 on 2021-03-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0004_auto_20210222_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='what_to_do',
            field=models.TextField(blank=True, help_text='hasbisbaosibaoib', null=True),
        ),
    ]
