# Generated by Django 3.1.5 on 2021-03-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0005_auto_20210301_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='what_to_do',
            field=models.TextField(blank=True, null=True),
        ),
    ]
