# Generated by Django 3.1.5 on 2021-03-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0006_auto_20210301_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
